### PR TITLE
Add all MRE components and contents, water bottle, matchbooks and packet, fortune cookie, add MRE to vendors

### PR DESCRIPTION
**Pull request by DrSmugleaf**
## About the PR
See #794 

## Media
https://github.com/CM-14/CM-14/assets/10968691/19d1789a-95d5-4c50-8e57-7a0ae7248f68

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
can the matches and cigs fit in the helmet?

**Comment by DrSmugleaf** [comment]
> can the matches and cigs fit in helmets?

Not yet, none of the helmets have a storage component.

**Comment by QuietlyWhisper** [comment]
> can the matches and cigs fit in helmets?

Adding onto this, do you know if its an itemslot or a full storage? Single item slots can be replaced instead of using storage, so you can just take and place into it, much like how the captains sabre and knife/pistol jackboots work now

**Comment by JoeHammad1844** [comment]
helmets are supposed to have 3 slots. by the way are slots supported in the current inventory system?

**Comment by QuietlyWhisper** [comment]
> helmets are supposed to have 3 slots. by the way are slots supported in the current inventory system?

That would just be a regular inventory then

**Comment by JoeHammad1844** [comment]
> > helmets are supposed to have 3 slots. by the way are slots supported in the current inventory system?
> 
> That would just be a regular inventory then

actually its more like 2 slots, the third is reserved for an accessory like broken NVG or a camo net

**Pull request merged**
