### PR TITLE
Make radio more readable on new chat

### PR DESCRIPTION
**Pull request by Skarletto**
## About the PR

Some radio channels were painfully unreadable with newchat, so I changed the colors of all radios, though most radios only got a little brighter. I think MP radio is the one I'm most unhappy with since it's kinda drab, but at least it's easier to tell which radio is which between MP and Alpha.
## Why / Balance

As we don't use the same kind of chat background as CM13 does, radio colors would benefit from an overhaul. This improves visibility and clarity. Also, we have like 4 brown~orange radios, so I tried making them more different for visibility. I don't know what Marine Common is, but I was assuming it were the Almayer radio, so I made it gray like on CM13.
## Technical details

nuffin major
## Media

gddhd
image (1)
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

nun

**Changelog**

:3

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
Looks a lot better yeah!

**Comment by Skarletto** [comment]
image
I'm having trouble with coloring MP, if anyone has suggestions lmk, but for now I will keep experimenting until I'm satisfied with the coloring

**Comment by Skarletto** [comment]
I'm going to assume tests failing are not my fault

**Review by QuietlyWhisper — APPROVED** [review]
Is good thanks

**Pull request merged**
