### PR TITLE
Militarypolice

### LINKED ISSUE #74: add all mp roles
- [ ] #75
- [ ] #76
- [ ] #77

### LINKED ISSUE #75: Chief MP
- [x] #78
- [x] #79
- [ ] #80
- [x] #81

### LINKED ISSUE #76: Warden
- [x] #82
- [ ] #83
- [x] #84
- [x] #85

### LINKED ISSUE #77: Military Police
- [x] #86
- [ ] #87
- [x] #88
- [x] #89

### LINKED ISSUE #78: Chief MP sprites

### LINKED ISSUE #79: Chief MP ftl

### LINKED ISSUE #80: Chief MP loadout

### LINKED ISSUE #81: Chief MP spawnpoint

### LINKED ISSUE #82: Warden sprites

### LINKED ISSUE #83: Warden loadout

### LINKED ISSUE #84: Warden ftl

### LINKED ISSUE #85: Warden spawnpoint

### LINKED ISSUE #86: Military Police sprites

### LINKED ISSUE #87: Military Police loadout

### LINKED ISSUE #88: Military Police ftl

### LINKED ISSUE #89: Military Police spawnpoint

### LINKED ISSUE #553: M2 Pattern MP Armor

### LINKED ISSUE #554: M3 Pattern Warden Armor
https://cm-ss13.com/wiki/Marine_Equipment#M3_Pattern_Warden_Armor

### LINKED ISSUE #555: M3 Pattern Chief MP Armor
https://cm-ss13.com/wiki/Marine_Equipment#M3_Pattern_Chief_MP_Armor

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

Adds Military Police department, Chief Military Police, Military Warden, Military Police with clothes for them.

## Why / Balance

Resolves #74, resolves #75, resolves #78, resolves #79, resolves #80, resolves #81, resolves #76, resolves #82, resolves #83, resolves #84, resolves #85, resolves #77, resolves #86, resolves #87, resolves #88, resolves #89, resolves #553, resolves #554, resolves #555

## Media

image_2023-11-14_23-26-34

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Tunguso4ka
- add: Chief MP, Military Warden and Military Police and clothes for them has been added to the game.
- add: Added black and brown marine gloves.
- add: Added black, brown and jungle combat boots

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
the fuck swaps file are doing there.

**Comment by QuietlyWhisper** [comment]
You'll probably need to leave a todo on the loadouts since we dont have all the entities yet unless you plan to port the rest

Idk if cm13 has mp belts or if they use security belts

**Comment by Tunguso4ka** [comment]
> You'll probably need to leave a todo on the loadouts since we dont have all the entities yet unless you plan to port the rest

i plan to also port backpacks and radios.

> Idk if cm13 has mp belts or if they use security belts

they have different texture on them, but thats secbelt.

**Comment by QuietlyWhisper** [comment]
> > You'll probably need to leave a todo on the loadouts since we dont have all the entities yet unless you plan to port the rest
> 
> i plan to also 
> they have different texture on them, but thats secbelt.

Alright no worries then, I think trying to make a child of the secbelt might have issues so it's fine for now

**Comment by Tunguso4ka** [comment]
well, for the sprites, ftl, spawnpoint, loadout all. (M2 armor needs tweaking i believe)
all is left is access.

**Comment by Tunguso4ka** [comment]
ready to review.

**Review by DrSmugleaf — APPROVED** [review]
The copyright field in the meta.jsons added here need to include a direct link to the source .dmi file with the commit instead of just the commit, and the entity prototypes should be inheriting from CMEntityBase, but I can fix both of those things tomorrow, thanks for the PR

**Comment by DrSmugleaf** [comment]
> oh. Merged before i fixed it. okay :(

Oh oops sorry, I was planning on fixing it tomorrow but if you want to do it you can open a new PR

**Pull request merged**
