### PR TITLE
Tables

### LINKED ISSUE #262: tables

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR
Ports 8 tables from cm13: standard table, 3 reinforced, 4 wooden tables.

## Why / Balance
Resolves #262 

## Media

image_2023-11-24_22-25-34

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
Ready to review.

**Review by DrSmugleaf — APPROVED** [review]

**Comment by JoeHammad1844** [comment]
no table flipping?

**Comment by Tunguso4ka** [comment]
> no table flipping?

no table flipping.

**Comment by JoeHammad1844** [comment]
thats an issue

**Pull request merged**
