### PR TITLE
Doors

### LINKED ISSUE #589: windows

### LINKED ISSUE #590: doors

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR
Adds doors:
- [x] Airlock assembly (sprites and prototype)
- [x] Personal door (sprites and prototype)
- [x] Personal glass door  (sprites and prototype)
- [x] Maintenance door  (sprites and prototype)
- [x] Command door (sprites and prototype)
- [x] Medical door (sprites and prototype)
- [x] Medical glass door (sprites and prototype)
- [x] Engineering door (sprites and prototype)
- [x] Engineering glass door (sprites and prototype)
- [x] Security door (sprites and prototype)
- [x] Security glass door (sprites and prototype)
- [x] Add accesses to the airlocks.

## Why / Balance
Resolves #590 

## Media

image_2023-11-23_11-59-13

image_2023-11-23_22-15-00

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
will do windoors in the different PR. Will be stupid to add windoors, but not the windows.

**Comment by Tunguso4ka** [comment]
Ready to review.

**Comment by Tunguso4ka** [comment]
also for the note,access configurator and painter does not works on cm airlocks.

**Comment by QuietlyWhisper** [comment]
> also for the note, access configurator and painter does not works on cm airlocks.

Shouldnt be needed

**Review by QuietlyWhisper — APPROVED** [review]
This doesn't include dropship and colony airlocks, which are not needed for first playtest and have made a second issue for. Thanks!

**Comment by JoeHammad1844** [comment]
double doors are also missing

**Pull request merged**
