### PR TITLE
Basic CM13 reagents

### LINKED ISSUE #813: CM13 reagents and healing value translation
## Description

so just clone the healing values from CM13
image
im doing this one (tomorrow after i post this)
https://www.youtube.com/watch?v=-_7FaWnlhS4

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

partially #813

what this DOES add
the heal amounts, OD's crit OD's and processing speed of
* bicaridine
* meralyn
* kelotane
* dermaline
* dexalin
* dexalin plus

what this does NOT add
* Localisation
* guidebook
* recipes (they're the same anyway)
* inaprovaline, inaprov does not exactly heal airloss, it only prevents it from becoming worse in crit

**Technical details**
CM chemicals have CM before the ID, E.G. CMbicaridine
CM chemicals have CM before the name in the locale thing E.G. reagent-desc-CM-bicaridine
all chemicals taste like themselves

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: JoeHammad
- add: ported some medicinal reagents from CM13

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
test fail erroneous

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Can't seem to bring up these chemicals in CM14 on your branch to see their colours etc, unlike the CM sodas. This is likely because the YML is invalid. Which is weird because the YML linter is passing despite errors..

For starters, 

- Rider is telling me the yml is wrong or something, see image (This is the case for every reagent in this pr)
image

- If the name/desc is just upstream like bicaridine's name, it can use upstream's localization and doesn't require unique localization
- Is one damage per unit correct? If I remember correctly cm13 chems use a scaling system which might require further investigation. If it's just a placeholder value, mark it with `# TODO CM14`.

I suppose when you're done with this if you're still interested you could also create the chemical reactions to make these new chems if they have any.

**Comment by JoeHammad1844** [comment]
> Can't seem to bring up these chemicals in CM14 on your branch to see their colours etc, unlike the CM sodas. This is likely because the YML is invalid. Which is weird because the YML linter is passing despite errors..
> 
> For starters,
> 
> * Rider is telling me the yml is wrong or something, see image (This is the case for every reagent in this pr)
>   image
> * If the name/desc is just upstream like bicaridine's name, it can use upstream's localization and doesn't require unique localization
> * Is one damage per unit correct? If I remember correctly cm13 chems use a scaling system which might require further investigation. If it's just a placeholder value, mark it with `# TODO CM14`.
> 
> Also on the todo list which can be completed in this PR
> 
> * You're missing the localization file for the reagent names and descriptions.
> 
> I suppose when you're done with this if you're still interested you could also create the chemical reactions to make these new chems if they have any.

bicaridine heals 1 brute damage and processes 0.2 units per second, this is how it's done in CM13

**Comment by JoeHammad1844** [comment]
havent worked on this for a long while and i likely wont again, feel free to re-use the code

**Comment by Simyon264** [comment]
I will try picking this up.

**Pull request closed without merging**
