### PR TITLE
Imported CM13 tips from a variety of sources and culled irrelevant SS14 tips.

### LINKED ISSUE #613: server tip messages
Either removed or remade to be relevant to cm14

https://github.com/cmss13-devs/cmss13/blob/236a44319009607869c05698d3215a3a1ebe9d40/strings/marinetips.txt#L34

### PR DESCRIPTION
**Pull request by thymol-blue**
## About the PR

- Removed irrelevant SS14 tips (xenoarchaeology, salvage, traitor, nukies, zombies, monkeys, engineering)
- Copied over ALL CM14 tips (marines, xeno, meta, memes) https://github.com/cmss13-devs/cmss13/blob/236a44319009607869c05698d3215a3a1ebe9d40/strings/marinetips.txt#L34
- Culled CM13 tips not relevant/will not be added anytime soon.
    - These are great new PR ideas that we may be missing. Added them as a comment at the bottom.
- Kept CM13 tips that I think will be reasonably added before the second playtest... hopefully.
- Added CM13 tips from the CM13 wiki and also CM13 reddit.
- Did not touch the CCVars.cs variables as I think a tip every 45 minutes in-round and 90 seconds out of the round is good.

## Why / Balance

Resolves #613 

## Technical details

Only changed the tips.yml to change what tips appear in-game.

You can test tips in-game by navigating to CM-14\Content.Shared\CCVar\CCVars.cs Line 480 and changing the tip system to be every 30 seconds or something (change it to like 60f * 0.5f).

## Media

Screenshot 2023-11-25 005931

Screenshot 2023-11-25 005824

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.

:cl:
- add: Added tips relevant to Colonial Marines 14. Be sure to keep an eye out for them!

## Discussion

1. What more tips should be added?
2. What more tips should be removed?
3. How do I set this up in the CM14 folder so it doesn't lead to merge conflicts. Not sure how to do it without changing the TipsSystem.cs file... but them wouldn't I need to move the TipsSystem.cs file into the CM14 folder 🤔

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
> 3. How do I set this up in the CM14 folder so it doesn't lead to merge conflicts. Not sure how to do it without changing the TipsSystem.cs file... but them wouldn't I need to move the TipsSystem.cs file into the CM14 folder 🤔

The best way to do this would be for us to have a new file with CM tips, then updating the `tips.dataset` cvar in the repository's config to point to that file. Then you can revert the changes to the original upstream tips file and we wouldn't get merge conflicts if tips are added or removed upstream, and it wouldn't require code changes to TipsSystem either.

**Comment by thymol-blue** [comment]
Well shit, I tried to revert the previous commit but I guess it just deleted itself. I guess I will leave it as a testament to my failures.

**Comment by DrSmugleaf** [comment]
> Well shit, I tried to revert the previous commit but I guess it just deleted itself. I guess I will leave it as a testament to my failures.

Force pushing after running `git reset` will erase the history, and if it leaves the branch without a commit it will make the PR automatically close. Running `git revert` will create a revert commit like normal.
If you haven't run many more git commands you may be able to run `git reflog` and then `git checkout HEAD@{...}` with an id to get the commit back.

**Comment by thymol-blue** [comment]
Ohh! That makes sense! I tried running "git revert" but it didn't seem to work so I tried instead to "git reset" then force push to see if that erased the old commit... which didn't work but in a way it did haha!

 If I pushed to origin will git revert work? I was doing "git revert [hash]" and it kept telling me:

image

**Comment by DrSmugleaf** [comment]
> Ohh! That makes sense! I tried running "git revert" but it didn't seem to work so I tried instead to "git reset" then force push to see if that erased the old commit... which didn't work but in a way it did haha!
> 
> If I pushed to origin will git revert work? I was doing "git revert [hash]" and it kept telling me:
> 
> image

You need to push after a revert yes, if you get that message it means that the commit was already reverted or for whatever other reason git thinks that reverting it wouldn't change any of your files

**Pull request closed without merging**
