### PR TITLE
Introducing: USS LCS-14 Savannah

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR
Adds a new USCM ship to the CM14: USS LCS-14 Savannah. Created specially for the first playtests of CM14.

I took inspiration in CM13 USS Almayer, real life America-class AASs and real life Independence-class LCSs.

## Media

зображення

Savannah-0

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by mmails** [comment]
first ever CM14 ship guys! 🤑🤑

**Comment by Tunguso4ka** [comment]
Tested it. runs good, arrival shuttle coming, light works, oxygen exists.

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
https://discord.com/channels/1168210010233376858/1168210011823026270/1183510602560319519

**Comment by Tunguso4ka** [comment]
> arrivals airlocks north and south are unpowered airlock escape pod at arrivals is unpowered lights in the gas miners are unpowered

done

**Comment by QuietlyWhisper** [comment]
image
buttons not linked to shutters

**Comment by QuietlyWhisper** [comment]
image
unpowered disposals south of hangar

**Comment by QuietlyWhisper** [comment]
image
these airlocks are not kitchen airlocks(?)

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
Besides the above comments, map seems ok

missing; 

- medbay treatment area; beds and whatnot
- research needs botany area
- marines have cryosleep rooms but not squad prep areas, where the equipment vendors would be, which is essential for making sure they use their own team's gear
  - marineprep access is used to get into the prep area, and squad access opens to their vendors

**Comment by Tunguso4ka** [comment]
> missing;
> 
>     * medbay treatment area; beds and whatnot

done

>     * research needs botany area

done

>     * marines have cryosleep rooms but not squad prep areas, where the equipment vendors would be, which is essential for making sure they use their own team's gear

plus minus done

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
unpowered light in a north substation room
image


unpowered light in ordnance
image


Some maints areas are very unlit, which is fine if you feel that's intended
image

Missing lv wires in south maints
image

Unpowered light in hallway to hangar
image


missing either direction of lv wire here + floating lightbulb
image

unpowered lightbulb in maints
image

wires that go nowhere + unpowered disposals
image

Disposals button linked to only work once
image

Do a check on all the red external airlocks, most are unpowered
image

equipment prep doors should be using these accesses per squad, which needs a new entity I think
image

These doors are fine however, they're locked to the basic prep access which correspondents can enter to talk to marines
image

The specialized roles like smartgunner, squad leader, etc are missing their setup rooms, but I'm not really sure where you're going to be able to put them with the amount of space there is, at those rooms need is the two or three relevant vendors if I remember right, they don't actually spawn there either
Alternatively they could just be in the same room and hopefully nobody steals their gear while they're trying to vend it

I think if you rename warp points the locations on maps and crew monitor will show correctly
image

I also think the whole ship could do with more lighting honestly, it feels dark in some places

**Comment by Tunguso4ka** [comment]
> unpowered light in a north substation room
> unpowered light in ordnance
> Missing lv wires in south maints
> Unpowered light in hallway to hangar
> missing either direction of lv wire here + floating lightbulb
> unpowered lightbulb in maints 
> wires that go nowhere + unpowered disposals
> Disposals button linked to only work once
> Do a check on all the red external airlocks, most are unpowered
> I think if you rename warp points the locations on maps and crew monitor will show correctly

will fix this

> equipment prep doors should be using these accesses per squad, which needs a new entity I think

i thought they did? will fix if im wrong.

> The specialized roles like smartgunner, squad leader, etc are missing their setup rooms, but I'm not really sure where you're going to be able to put them with the amount of space there is, at those rooms need is the two or three relevant vendors if I remember right, they don't actually spawn there either

I'm gonna pray for humanity to not steal other peoples stuff.

> Some maints areas are very unlit, which is fine if you feel that's intended
> I also think the whole ship could do with more lighting honestly, it feels dark in some places

It's intended like this to "be more atmospheric". I played Alien Isolation again last week. I think it makes it more scary to go around alone, not knowing what or even who is in the shadows.

will fix it if it bothers you.

**Comment by Tunguso4ka** [comment]
something something with the test.

**Comment by QuietlyWhisper** [comment]
> It's intended like this to "be more atmospheric". I played Alien Isolation again last week. I think it makes it more scary to go around alone, not knowing what or even who is in the shadows.
> 
> will fix it if it bothers you.

it would be preferred if the ship was well lit since marines are the ones that will be on the ship most often

however for a map design of a ship overtaken by xenos where marines need to clear it out, that would be a great design plan

**Comment by Tunguso4ka** [comment]
> it would be preferred if the ship was well lit since marines are the ones that will be on the ship most often

affirmative, will add more lights.

**Comment by QuietlyWhisper** [comment]
I can't seem to launch the map with the force map command. It's exclusively an issue with this map after testing

**Comment by Tunguso4ka** [comment]
> I can't seem to launch the map with the force map command. It's exclusively an issue with this map after testing

will fix it when i`l have a time.

**Comment by Tunguso4ka** [comment]
Ready to review.

**Comment by JoeHammad1844** [comment]
> Tested it. runs good, arrival shuttle coming, light works, oxygen exists.

arrivals shuttle? arent people supposed to wake up from cryo pods?

**Review by QuietlyWhisper — DISMISSED** [review]

**Review by QuietlyWhisper — APPROVED** [review]

**Comment by Tunguso4ka** [comment]
thanks for the commits Whisper <3

**Pull request merged**
