### PR TITLE
Tweak Storages

### PR DESCRIPTION
**Pull request by Froffy025**
## About the PR

Allow magazines in ammo rig, change webbing size, add storage to helmet, changed the size of some items
## Why / Balance

Things I remember from CM13 that people will probably want
## Media

image backpack
image webbing
image helmet
image ammo carry rig
image remember who you're fighting for

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 
- Tweaked grid size for webbing
- Made some items smaller
- Added helmet storage

### CODE REVIEW

**Comment by Froffy025** [comment]
image
injector pouch

**Review by QuietlyWhisper — CHANGES_REQUESTED** [review]
We're looking at item sizes right now, take those changes out and leave helmet storage and the whitelist fix thank you!

**Comment by Froffy025** [comment]
OK. sizes removed o7

**Review by QuietlyWhisper — APPROVED** [review]
Thanks

**Pull request merged**
