### PR TITLE
Resize all job icons

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

Resized all job icons to 16x16.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
files changed 115, but theres 117 files in cm_job_icons. fuck.

**Comment by DrSmugleaf** [comment]
> files changed 115, but theres 117 files in cm_job_icons. fuck.

You are missing [rmc_smartgunner.png](https://github.com/CM-14/CM-14/blob/a3da3116a43e95cecff75e099eb8c37c82febe93/Resources/Textures/_CM14/Interface/cm_job_icons.rsi/rmc_smartgunner.png) and [hudsquad_soctl_a.png](https://github.com/CM-14/CM-14/blob/a3da3116a43e95cecff75e099eb8c37c82febe93/Resources/Textures/_CM14/Interface/cm_job_icons.rsi/hudsquad_soctl_a.png)
You can double check by viewing the cm_job_icons.rsi folder at your branch on GitHub: https://github.com/CM-14/CM-14/tree/a3da3116a43e95cecff75e099eb8c37c82febe93/Resources/Textures/_CM14/Interface/cm_job_icons.rsi

**Comment by Tunguso4ka** [comment]
ready to review.

**Review by DrSmugleaf — APPROVED** [review]
I have to check how these look in-game and their centering but it's a lot better than before, thanks for the PR

**Pull request merged**
